/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

function Model(props) {
    const { nodes, materials } = useGLTF('/models/machine.gltf')
    return (
        <group {...props} dispose={null}>
            <group position={[-0.0018, 0.0003, -0.0004]} rotation={[-Math.PI / 2, 0, 0]} scale={0.4749}>
                <group position={[-0.0038, 0.0002, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.9981}>
                    <group position={[-0.0038, 0, -0.0002]} scale={0.1812}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.geometryElement15.geometry}
                            material={materials.Texture_Reja}
                            position={[-0.0212, 0, -0.0006]}
                            scale={0.9981}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.geometryElement16.geometry}
                            material={materials.Texture_Volantin}
                            position={[-0.0212, 0, -0.0006]}
                            scale={0.9981}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.geometryElement17.geometry}
                            material={materials.Texture_Puerta3}
                            position={[-0.0212, 0, -0.0006]}
                            scale={0.9981}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.geometryElement18.geometry}
                            material={materials.Texture_Puerta2}
                            position={[-0.0212, 0, -0.0006]}
                            scale={0.9981}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.geometryElement19.geometry}
                            material={materials.Texture_Puerta1}
                            position={[-0.0212, 0, -0.0006]}
                            scale={0.9981}
                        />
                    </group>
                </group>
            </group>
            <group position={[-0.0016, 0, -0.0005]} rotation={[-Math.PI, 0.9093, -Math.PI]} scale={0.189}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Rover_Wheel001.geometry}
                    material={materials['Wheel grey brown']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Rover_Wheel001_1.geometry}
                    material={materials['Wheel white']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Rover_Wheel001_2.geometry}
                    material={materials['Wheel black']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Rover_Wheel001_3.geometry}
                    material={materials.Aluminioum}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Rover_Wheel001_4.geometry}
                    material={materials['Wheel black']}
                />
            </group>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.body.geometry}
                material={materials.Texture_Puerta2}
                position={[0.01, 0, 0.22]}
                scale={[0.3248, 0.8407, 0.4048]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.electronics.geometry}
                material={materials.Texture_Puerta2}
                position={[-0.5016, 0.8614, -0.3527]}
                scale={[0.3547, 0.8404, 0.3847]}
            />
            <group position={[-0.52, 0.24, -0.29]} rotation={[Math.PI, -1.3788, Math.PI]} scale={6}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.mesh010.geometry}
                    material={materials.glimmer}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.mesh010_1.geometry}
                    material={materials['Material.008']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.mesh010_2.geometry}
                    material={materials['chrome-w.002']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.mesh010_3.geometry}
                    material={materials['rÖHRICH.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.mesh010_4.geometry}
                    material={materials['chrome-w.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.mesh010_5.geometry}
                    material={materials['Material.004']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.mesh010_6.geometry}
                    material={materials['Material.005']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.mesh010_7.geometry}
                    material={materials['chrome-w.003']}
                />
            </group>
        </group>
    )
}

export default Model;

useGLTF.preload('/models/machine.gltf')
